language: android
android:
  components:
  
     - platform-tools
     - tools

   
    - build-tools-23.0.0

   
    - android-23

   
    
    - extra-android-support
  
before_install:
    - chmod +x gradlew

 
