language: android
sudo: required
android:
  components:
    - tools

    - build-tools-25.0.1
    - android-25
    - extra-android-support
    - extra-android-m2repository
  licenses:
    - 'android-sdk-license-.+'
    - '.*intel.+'
jdk:
  - oraclejdk8
  before_install:
  - sudo apt-get update && sudo apt-get install oracle-java8-installer
  - chmod +x gradlew
  - git submodule update --init --recursive
script:
  
  - ./gradlew build check
